### ISSUE TITLE
Generator V3

### ISSUE THREAD

**Issue by slajax** [feathersjs/feathers-generator#19]
## overview

This epic includes all of the work needed to get to a stable v2 of the generator and cli.

## goals
- [x] fix service generation defaults introduced in #10 
- [x] service models should be configurable via prompts and templates
- [x] implement feathers-nedb
- [x] implement feathers-memory
- [x] implement feathers-mongoose
- [x] implement feathers-rethinkdb
- [x] use `service.json`
- [x] use `feathers.json`
- [x] support database initiation
- [x] support handlebars
- [x] implement hooks generator
- [x] implement filters generator
- [x] implement middleware generator
- [x] implement plugin generator
- [x] implement repo generator
- [x] implement semi-standard
- [x] implement auto testing when generating
- [x] implement docker support
- [x] implement feathers-knex
- [x] implement feathers-sequelize
- [x] implement feathers-mongodb
- [x] configure logging
- [ ] implement feathers-elasticsearch
- [ ] better test coverage
- [ ] readme + documentation

## technical debt
- [x] update app templates for eslint + semistandard
- [ ] model configuration based on model `meta.json`
- [ ] refactor some of the duplicate service middleware into base utils
- [ ] fix up todos added in #10

**Comment by kristianmandrup** [comment]
What is the status on v3? I'm trying to add Koa REST support [here](https://github.com/kristianmandrup/feathers-rest-koa)

**Comment by slajax** [comment]
@kristianmandrup we decided to sunset it.

**Comment by kristianmandrup** [comment]
Sunset feathers v3 entirely? what is the plan then going forward?

**Comment by slajax** [comment]
In its current implementation, yes. V2 has been under continuous development so the generator will continue to live on but not under the direction represented here. V3 will likely be more backwards compatible and not require so many changes to how the underlying code is orchestrated.
